version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu/codedeploy

hooks:
  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 300

  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 300