version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          name: Install the dependencies 
          command: 'npm install'
      - run: 
          name: run the unit test
          command: 'npm test' 

  build:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          name: Installing packages
          command: 'npm install'
      - run: 
          name: run the unit test
          command: 'npm test'
  
  deploy:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout        
      - run:
          name: Updating apt-get
          command: sudo apt-get update
      - run:
          name: Installing wget
          command: 'sudo apt-get install wget zip unzip'
      - run:
          name: Install node dependencies 
          command: | 
            npm install 
      - run:
          name: Installing aws cli
          command: | 
            sudo apt-get install python-pip  
            sudo pip install awscli
      - run:
          name: Install less
          command: |
            echo "Install less dependency"
            sudo apt-get update
            sudo apt-get install less -y
      - run:
          name: Build Deployment Artifact
          command:  |
            cd ~/
            mkdir -p codedeploy_artifact
            cd project
            echo RDS_HOSTNAME = $RDS_HOSTNAME > rds.txt
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip *
            pwd
            ls -al
            mv webapp-${CIRCLE_BUILD_NUM}.zip  ~/codedeploy_artifact/
            ls -al
            pwd
            cd ~/codedeploy_artifact
            ls -al
      - run: 
          name: Copy artifact to S3
          command: |
            aws s3 cp /home/circleci/codedeploy_artifact/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://${S3_BUCKET_NAME}
      - run: 
          name: CodeDeploy API call
          command: |
            aws deploy register-application-revision \
              --application-name csye6225-webapp \
              --s3-location bucket=${S3_BUCKET_NAME},bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip --region us-east-1
            
            aws deploy create-deployment \
            --application-name csye6225-webapp \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name csye6225-webapp-deployment \
            --s3-location bucket=${S3_BUCKET_NAME},bundleType=zip,key=artifacts/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip --region us-east-1
        

workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
    
  build:

    jobs:
    - build:
        filters:
          branches:
            only: master
  deploy:
    jobs:
      - deploy
    # - deploy:
    #     filters:
    #       branches: