version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          name: Install the dependencies 
          command: 'npm install'
      - run: 
          name: run the unit test
          command: 'npm test' 

  build:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          name: Installing NPM
          command: 'npm install' 
      - run: 
          name: run the unit test
          command: 'npm test' 


workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
    
  build:

    jobs:
    - build:
        filters:
          branches:
            only: master
    # - deploy:
    #     filters:
    #       branches:
    #         only: master            